### ISSUE TITLE
[infra] definir novo schema para a BD

### ISSUE THREAD

**Issue by d116626** [basedosdados/website#34]
Estrutura de pastas do `validation`:

```yaml
package
    ckan_default_package
    dataset                                   [dataset.yaml]
resource
    ckan_default_resource
    bdm
        table                                 [table.yaml]
        columns                               [table.yaml]
        dictionary
    information_request         
    external_link			      [dataset.yaml]
```
* entre [] os arquivos atuais que contém a informação

**Comment by rdahis** [comment]
O schema abaixo será continuamente iterado até fecharmos as validações.

Fonte discutida com o @polvoazul, que inclui mais informações sobre cada campo: https://github.com/basedosdados/website/blob/c814e38c1fb5c5bbad7d118d071bf81a0f1b962b/ckanext-basedosdados/ckanext/basedosdados/scheming_metadata_definitions_v2.yaml

**dataset**
```yaml
dataset_id:
  - derived: no
title:
  - derived: no
description:
  - derived: no
tag_string:
  - derived: no
organization_id:
  - derived: no
download_type:
  - derived: yes
spatial_coverage:
  - derived: yes
time_coverage:
  - derived: yes
entity:
  - derived: yes
time_unit:
  - derived: yes
auxiliary_files_url:
  - derived: no
```

**bdm_table**
```yaml
dataset_id:
table_id:
description:
spatial_coverage:
time_coverage:
update_frequency:
treatment_description:
entity:
time_unit:
identifying_columns:
last_updated_metadata:
last_updated_data:
last_released:
version:
publisher_name:
publisher_email:
publisher_github:
publisher_website:
raw_data_url:
architecture_table_url:
covered_by_dictionary:
```

**column**
```yaml
name:
type:
description:
time_coverage:
has_dictionary:
directory_column:
measurement_unit:
original_names:
```

**dictionary**
```yaml
dataset_id:
table_id:
last_updated:
```

**external_link**
```yaml
url:
description:
language:
has_api:
is_free:
requires_registration:
availability:
requires_brazilian_ip:
license_type:
spatial_coverage:
time_coverage:
entity:
update_frequency:
```

**information_request**
```yaml
origin:
number:
url:
superior_organ:
linked_organ:
opening_date:
who_requested:
status:
spatial_coverage:
time_coverage:
entity:
update_frequency:
data_url:
observations:
```
